services:
  frontend-server:
    image: nginx:stable
    container_name: frontend-server
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/:/var/www/html/:ro
    depends_on:
      - backend-server
    
  backend-server:
    container_name: backend-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"

