services:
  nginxwebsvr:
    image: nginx:alpine
    container_name: nginxwebsvr
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/var/www/html/:ro
    networks:
      - my_network
    ports:
      - "8080:80"

networks:
    my_network:
      driver: bridge