name: Node.js Selenium Testing

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ./frontend/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules

      - name: Install Node.js dependencies
        run: npm install --prefix ./frontend

  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: node:20

    env:
      SELENIUM_REMOTE_URL: http://selenium:4444/wd/hub
      APP_URL: http://localhost:5173

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install --prefix ./frontend

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --prefix ./frontend

      - name: Build React app
        run: npm run build --prefix ./frontend

      - name: Start Vite dev server in background
        run: |
          npm run dev --prefix ./frontend -- --host &
          echo "Vite server started"
        shell: bash

      - name: Wait for Vite to be ready
        run: |
          for i in {1..10}; do
            if curl -s $APP_URL > /dev/null; then
              echo "Vite is up!"
              break
            else
              echo "Waiting for Vite..."
              sleep 3
            fi
          done

      - name: Wait for Selenium
        run: |
          for i in {1..10}; do
            if curl -s -o /dev/null -w "%{http_code}" $SELENIUM_REMOTE_URL | grep -q "200"; then
              echo "Selenium is ready!"
              break
            else
              echo "Waiting for Selenium..."
              sleep 3
            fi
          done

      - name: Run Selenium tests
        run: |
          # run your test command here, e.g.:
          node ./frontend/selenium_testing/login_testing.js